### ISSUE TITLE
quickstart guide

### ISSUE THREAD

**Issue by arlted** [siliconcompiler/siliconcompiler#1066]
I received an error while running the following command from the tutorial. Could you please point out what i am missing?
 
Command:  python -c "import siliconcompiler;chip=siliconcompiler.Chip();print(chip.get('version','sc'))"

Error message:
.../venv/lib64/python3.6/site-packages/siliconcompiler/crypto.py:3: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
  from cryptography.hazmat.backends import default_backend
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: __init__() missing 1 required positional argument: 'design'

**Comment by nmoroze** [comment]
Sorry about that, we've had some API changes since so the docs are currently incorrect. 

I think the new equivalent would be:

```
python -c "import siliconcompiler;print(siliconcompiler.__version__)
```

I'll leave this issue open until we fix the docs.

**Comment by arlted** [comment]
Thanks, the new command works.
However, I got the following error during synthesis. Anything I am missing?

| INFO    | job0  | syn        | 0  | Tool 'yosys' found with version '/lib64/libstdc++.so.6:' in directory '/data/Software/yosys/0.17/bin'
| ERROR   | job0  | syn        | 0  | Version /lib64/libstdc++.so.6: reported by yosys does not match standard.
| ERROR   | job0  | syn        | 0  | normalize_version() returned invalid version /lib64/libstdc--.so.6:
| ERROR   | job0  | syn        | 0  | Halting step 'syn' index '0' due to errors.


Thanks,
Ted


________________________________
From: Noah Moroze ***@***.***>
Sent: Wednesday, June 29, 2022 10:34 AM
To: siliconcompiler/siliconcompiler ***@***.***>
Cc: Nigussie, Theodros B CIV USARMY DEVCOM ARL (USA) ***@***.***>; Author ***@***.***>
Subject: [URL Verdict: Neutral][Non-DoD Source] Re: [siliconcompiler/siliconcompiler] quickstart guide (Issue #1066)


All active links contained in this email were disabled. Please verify the identity of the sender, and confirm the authenticity of all links contained within the message prior to copying and pasting the address to a Web browser.


________________________________



Sorry about that, we've had some API changes since so the docs are currently incorrect.

I think the new equivalent would be:

python -c "import siliconcompiler;print(siliconcompiler.__version__)

I'll leave this issue open until we fix the docs.

**Comment by nmoroze** [comment]
That looks to me like a problem with your Yosys installation. Is there an error message when you just run `yosys` directly from the command line?

**Comment by arlted** [comment]
Never mind this issue.
The module loader on my machine failed to load gcc and that was the cause of the problem. Now, with the correct loading, yosys runs smoothly.
Thanks for looking into this!

Ted
________________________________

**Comment by nmoroze** [comment]
Got it, glad to hear!

**Comment by arlted** [comment]
yes, i get the following error when i ran yosys from the command line.  will look into this.

(venv) [tutorial]$ yosys
yosys: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by yosys)
yosys: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by yosys)
yosys: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by yosys)


________________________________
From: Noah Moroze ***@***.***>
Sent: Thursday, June 30, 2022 1:50 PM
To: siliconcompiler/siliconcompiler ***@***.***>
Cc: Nigussie, Theodros B CIV USARMY DEVCOM ARL (USA) ***@***.***>; Author ***@***.***>
Subject: [URL Verdict: Neutral][Non-DoD Source] Re: [siliconcompiler/siliconcompiler] quickstart guide (Issue #1066)


All active links contained in this email were disabled. Please verify the identity of the sender, and confirm the authenticity of all links contained within the message prior to copying and pasting the address to a Web browser.


________________________________



That looks to me like a problem with your Yosys installation. Is there an error message when you just run yosys directly from the command line?
