### ISSUE TITLE
Unable to run heartbeat example - can't find third party libs

### ISSUE THREAD

**Issue by SeyiAyoARL** [siliconcompiler/siliconcompiler#1068]
In running the heartbeat example, I'm receiving the following error:

FileNotFoundError: [Errno 2] No such file or directory: '../third_party/pdks/virtual/freepdk45/libs/nangate45/r1p0/lib/NangateOpenCellLibrary_typical.lib'

I believe this is probably related to an earlier issue (Relative path change #1014).

Thank you!

**Comment by nmoroze** [comment]
Have you cloned the siliconcompiler repo and set your SCPATH variable pointing to it? I think missing that step would cause this issue.

See the "Note" box under https://docs.siliconcompiler.com/en/latest/user_guide/quickstart.html#setup.
