### ISSUE TITLE
summary generates error

### ISSUE THREAD

**Issue by arlpetergadfort** [siliconcompiler/siliconcompiler#1072]
On RHEL7 with Python3.6 I get the following error if I have the summary printed:
```
Traceback (most recent call last):
  File "examples/gcd/gcd-intel.py", line 83, in <module>
    main(root='examples/gcd')
  File "examples/gcd/gcd-intel.py", line 80, in main
    chip.summary()
  File "/data/Software/siliconcompiler/0.9.1/siliconcompiler/core.py", line 3163, in summary
    img_data = img_data,
UnicodeEncodeError: 'ascii' codec can't encode characters in position 7961-7962: ordinal not in range(128)
```

**Comment by nmoroze** [comment]
Interesting, I'll look into this. There should be a .png file in your build directory (will probably be something like `build/gcd/job0/gcd.png`) -- if you're comfortable/able to send that to noah@zeroasic.com, that would be helpful!

**Comment by arlpetergadfort** [comment]
That file is not there either

**Comment by nmoroze** [comment]
That's odd. Are you able to send the gcd-intel.py script? Are you using a custom flow and/or PDKs/libs? I think I'll need more information to work out what's going on here.
