### ISSUE TITLE
Surelog fails to parse parameter with partial vector select

### ISSUE THREAD

**Issue by aolofsson** [siliconcompiler/siliconcompiler#1117]
There seems to be an issue with the surelog parser for partial parameter selections. It's a problem because we rely on surelog to help us bring in files to the next step. 

https://github.com/chipsalliance/Surelog/issues/3133

I have veriried that the design goes through yosys with verilator as the front end parser.

**Comment by mithro** [comment]
FYI - @hzeller / @kgugala

**Comment by aolofsson** [comment]
Problem solved by updating to surelog 1.35.  

@nmoroze @WRansohoff This is a show stopper for the code I am working on, can we update SC with the latest surelog?

**Comment by nmoroze** [comment]
Yeah, I can prep something to bump the Surelog. You might have been hoping to avoid this, but SC will use a Surelog on your PATH instead of the bundled one if you want to build the new version yourself in the meantime.

**Comment by aolofsson** [comment]
Yes, already did on my machine. Still, figured we should update since this is a showstopper for some designs.

**Comment by nmoroze** [comment]
Yup, absolutely. Just wanted to make sure you weren't blocked :)
