### ISSUE TITLE
SKY90 ? 

### ISSUE THREAD

**Issue by vetter** [siliconcompiler/siliconcompiler#1127]
What are your plans for supporting SKY90? Thanks, 
/jeff

**Comment by mithro** [comment]
The SKY90FD PDK is not yet released. I'm sure that SiliconCompiler will explore support when things like that are available.

**Comment by vetter** [comment]
@mithro : Thanks. we are currently targetting SKY130; will SKY90FD be a compatible swap in these open source tool chains (silicon compiler, openlane)?

**Comment by mithro** [comment]
@vetter - Unclear at the moment (Bulk verse FDSOI offers some unique challenges), but we will try and make moving between technologies as easy as possible.

**Comment by aolofsson** [comment]
Once thesky90 is reased, we will do our best to support it!
