### ISSUE TITLE
Make `check_logfile()` quieter

### ISSUE THREAD

**Issue by nmoroze** [siliconcompiler/siliconcompiler#1132]
Currently `check_logfile()` will log all errors/warnings found after a step runs when `['option', 'quiet']` is False. I've found this pretty annoying when I'm getting many warnings since it obscures the tool logs. 

A couple options to consider:
- Reverse the polarity on this call to only display when "quiet" is ON. This might sound a little counterintuitive, but when quiet is off then you can see the warnings in the tool logs anyways, so in some sense it seems more useful to repeat them if the tool logs aren't being printed.
- Limit the count of warnings/errors printed
- Disable the display entirely

**Comment by gadfort** [comment]
Closing stale issue
