### ISSUE TITLE
Rethinking site/footprint in schema

### ISSUE THREAD

**Issue by nmoroze** [siliconcompiler/siliconcompiler#1136]
A couple things seem off about how we're doing this now, with per-library entries in ['asic', 'footprint']:

- Some PDKs specify sites in the tech LEF, while sometimes sites are defined in an individual macro LEF. We should probably add a place for site in PDK schema.
- Need a place to specify default. Maybe ['asic', 'defaultfootprint']?

**Comment by gadfort** [comment]
Closing stale issue
