### ISSUE TITLE
[MacOS only] openroad cmake-build error: undeclared identifier 'lefyyparse'

### ISSUE THREAD

**Issue by jldec** [siliconcompiler/siliconcompiler#1262]
On an M1 Mac running Ventura and xcode command line utilities and Python v3.10.9  
Following the clone + build instructions in the docs at
https://docs.siliconcompiler.com/en/latest/user_guide/installation.html#siliconcompiler

When running `python -m pip install -e .` the build failed with  

> zeroasic/sc/siliconcompiler/_skbuild/macosx-13.0-arm64-3.10/cmake-build/_deps/openroad-src/src/odb/src/lef/lef/lefrReader.cpp:297:12: error: use of undeclared identifier 'lefyyparse'

A google search led to https://github.com/The-OpenROAD-Project/OpenROAD/issues/1688 (@nmoroze). I followed the suggested advice in the [comment](https://github.com/The-OpenROAD-Project/OpenROAD/issues/1688#issuecomment-1087744398), and brew installed bison and flex (with override of the existing /usr/bin flavors).

This resolved the error 😄 

Perhaps adding a troubleshooting section to the docs or README would help others who run into this.

**Comment by nmoroze** [comment]
Thanks for opening this issue! We'll make a note in the docs.
