### ISSUE TITLE
Could not find target

### ISSUE THREAD

**Issue by techstuds** [siliconcompiler/siliconcompiler#1505]
Hi, 
I tried to setup a new pdk (by creating a new target at first) but facing this error when I run the heartbeat-example with the new target:
    siliconcompiler.core.SiliconCompilerError: Could not find target pdk_demo

pdk_demo.py is the target which I created in siliconcompiler/siliconcompiler/targets

Any solution for this? 

Thanks
Nils

**Comment by gadfort** [comment]
@techstuds what version of siliconcompiler are you using? If there is a syntax error in pdk_demo it might fail to import.
In the most recent version 0.11.0 you can do:
```
from siliconcompiler.targets import pdk_demo

.....

chip.load_target(pdk_demo)
```

**Comment by techstuds** [comment]
Thank you @gadfort, this worked (version 0.11.0).
