### ISSUE TITLE
Invalid keypath / unexpected key

### ISSUE THREAD

**Issue by techstuds** [siliconcompiler/siliconcompiler#1510]
Hi, during the setup of a new pdk I'm facing this error related to the lib.py file which I created in siliconcompiler/libs:

`siliconcompiler.core.SiliconCompilerError: Invalid keypath ('library', 'lib_pdk', 'option', 'file', 'yosys_dff_liberty'): unexpected key: lib_pdk`

Any solution for this?

Thanks

**Comment by gadfort** [comment]
This is likely the issue what was resolved in: https://github.com/siliconcompiler/siliconcompiler/commit/b83c592e55313154e9b908c07206875c954dbd41

You could clone the repo and install from there, but we should be generating a new version tag soon which would include this fix.

**Comment by gadfort** [comment]
It looks like it's trying to find the standard cell library but it's not finding it. I would check that the liberty files are setup correctly

**Comment by gadfort** [comment]
There is a check missing in the code (which I'll put in a PR for). 
But either you do not have timing constraints setup and the `synthesis_corner` is getting set to None as well or some unknown value or you have no liberty files defined for the synthesis corner. Those are the likely issues.

**Comment by techstuds** [comment]
Thanks @gadfort! I updated siliconcompiler/tools/yosys/syn_asic.py with your latest version. Now it's running trough the setup for yosys but getting stuck in setup for openroad:

`File "./heartbeat.py", line 17, in <module>
    main()
  File "./heartbeat.py", line 12, in main
    chip.run()                                # run compilation
  File "/home/docker/venv/lib/python3.8/site-packages/siliconcompiler/core.py", line 4248, in run
    self._setup_task(step, index)
  File "/home/docker/venv/lib/python3.8/site-packages/siliconcompiler/core.py", line 4009, in _setup_task
    raise e
  File "/home/docker/venv/lib/python3.8/site-packages/siliconcompiler/core.py", line 4006, in _setup_task
    setup_step(self)
  File "/home/docker/venv/lib/python3.8/site-packages/siliconcompiler/tools/openroad/floorplan.py", line 11, in setup
    setup_tool(chip)
  File "/home/docker/venv/lib/python3.8/site-packages/siliconcompiler/tools/openroad/openroad.py", line 67, in setup
    libtype = chip.get('library', mainlib, 'asic', 'libarch', step=step, index=index)
  File "/home/docker/venv/lib/python3.8/site-packages/siliconcompiler/core.py", line 880, in get
    self.error(str(e))
  File "/home/docker/venv/lib/python3.8/site-packages/siliconcompiler/core.py", line 4978, in error
    raise SiliconCompilerError(msg) from None
siliconcompiler.core.SiliconCompilerError: Invalid keypath ('library', 'lib_pdk', 'asic', 'libarch'): unexpected key: lib_pdk`

Maybe it's something similar to the first problem I mentioned?

**Comment by gadfort** [comment]
@techstuds would you be able to share a testcase for this or your manifest? If so, `sc-issue -generate -cfg ./build/../../floorplan/0/inputs/<>.pkg.json -arg_step floorplan -arg_index 0` and upload the tarball.
If not, it seems like something similar, but I think your library is not configured correctly for openroad.

**Comment by techstuds** [comment]
Unfortunately no build directory was created but here are the files I created. Maybe you find a mistake?

[libs_xt011.py.txt](https://github.com/siliconcompiler/siliconcompiler/files/11374908/libs_xt011.py.txt)
[pdk_xt011.py.txt](https://github.com/siliconcompiler/siliconcompiler/files/11374910/pdk_xt011.py.txt)
[xt011_demo.py.txt](https://github.com/siliconcompiler/siliconcompiler/files/11374911/xt011_demo.py.txt)

**Comment by techstuds** [comment]
I changed the name for clarity, so `lib_pdk` is `libs_xt011` now. I invoke sc by running the example heartbeat.py with my own target `xt011_demo`. 

I checked the two issues you mentioned and you were right, synthesis is running now and I'll keep going. Thank you @gadfort !
