### ISSUE TITLE
Unable to use 'sc' in windows - Powershell

### ISSUE THREAD

**Issue by shariethernet** [siliconcompiler/siliconcompiler#1547]
`sc` is a keyword that stands for 'Set-Content` in Windows PowerShell

**Comment by gadfort** [comment]
@shariethernet that's an unfortunate collision.
It looks like you can run: `Del -Force alias:sc` or `Remove-Alias -Force sc` to remove that alias from your current session of PowerShell. That should expose the installed siliconcompiler (assuming your path has it in there).
You can run `Get-Command -Type All sc` to see all the commands for sc and the in the order they will be selected.
In a virtual environment I was able to use sc in powershell after I removed the alias.

**Comment by shariethernet** [comment]
Thanks. That solves the issue. However, sc also is responsible to interact with Windows Service Controller, so an option of offering silicon compiler's sc to be called by another alias would be great.
