### ISSUE TITLE
Mac dynamic library libc++.1.0.dylib needed by surelog

### ISSUE THREAD

**Issue by mayagokhale** [siliconcompiler/siliconcompiler#1732]
siliconcompiler install puts a pre-built surelog into the venv siliconcompiler tool surelog bin directory if an existing surelog binary is not found. on the Mac, this binary expects a Monterey libc++.1.0.dylib in /usr/lib. On other versions of MacOS (such as Big Sur), that library doesn't exist and surelog --version fails.
Luckily I had this library in a different location under anaconda, and adding the path to it to DYLD_LIBRARY_PATH solved the problem. 
I'm submitting this as an issue in case you want to add the fix information to the siliconcompiler build instructions.

**Comment by nmoroze** [comment]
Hi, thanks for opening the issue! When you get a chance, could you please send the exact error message you get when running `surelog --version` without the updated library path?

**Comment by mayagokhale** [comment]
venv/lib/python3.11/site-packages/siliconcompiler/tools/surelog/bin/surelog --version
dyld: Symbol not found: __ZTTNSt3__114basic_ifstreamIcNS_11char_traitsIcEEEE
  Referenced from: /Users/gokhale2/src/siliconcompiler/venv/lib/python3.11/site-packages/siliconcompiler/tools/surelog/bin/surelog (which was built for Mac OS X 12.6)
  Expected in: /usr/lib/libc++.1.dylib

**Comment by nmoroze** [comment]
Thanks! I've attached a recompiled binary that I expect to work on Big Sur as-is, it would be helpful if you could un-gzip and try it out.

[surelog.gz](https://github.com/siliconcompiler/siliconcompiler/files/12114596/surelog.gz)

**Comment by mayagokhale** [comment]
./surelog --version
VERSION: 1.69
BUILT  : Jul 20 2023
