### ISSUE TITLE
Missing route to pin

### ISSUE THREAD

**Issue by techstuds** [siliconcompiler/siliconcompiler#1768]
I'm facing this warning for all connections except the clocktree. I'm attaching the route.log, maybe there is something useful in there. 

Thanks for your help!

[route.log](https://github.com/siliconcompiler/siliconcompiler/files/12052366/route.log)

**Comment by gadfort** [comment]
@techstuds it's a warning from OpenROAD that relates to the extraction of the parasitics. It's a poorly phrased message, but you have routing, just the extractor is expecting that route to hit a specific part of the pins which is may not do.

**Comment by techstuds** [comment]
@gadfort Alright thanks!
