### ISSUE TITLE
Error while running the asic demo

### ISSUE THREAD

**Issue by prathiksha97** [siliconcompiler/siliconcompiler#2036]
![image](https://github.com/siliconcompiler/siliconcompiler/assets/69187224/cf740876-001f-4730-aa75-4a31795b9fc5)
I am getting an error when I try to run the asic demo.
I am on Ubuntu 22.04 and the python version I am using is 3.10.13
Can anyone please help me with this

**Comment by WRansohoff** [comment]
Hi there,

Sorry for the inconvenience. There is a bug in the client with v0.16.0 which causes the remote flow not to work. We should have a patch shortly.

If you are able to modify your installation, you should be able to work around the issue by replacing [the following two lines here](https://github.com/siliconcompiler/siliconcompiler/blob/7eaaaaba52daf418850233565b92a3f9f18045c2/siliconcompiler/remote/client.py#L173):

```
-     chip.set('arg', 'step', preset_step)
-     chip.set('arg', 'index', preset_index)
+    chip.set('option', 'from', 'syn')
+    chip.set('option', 'to', 'export')
```

We should have a more complete fix soon. Thank you for trying SiliconCompiler, and sorry again for the confusion.

**Comment by gadfort** [comment]
@prathiksha97 @Vinayakamk a new release with the fix was pushed: https://github.com/siliconcompiler/siliconcompiler/releases/tag/v0.16.1

**Comment by prathiksha97** [comment]
Thank you, It is working!
