### ISSUE TITLE
siliconcompiler._common.SiliconCompilerError: Server responded with 400: Error: Submitted jobs must use Schema version 0.37.x. Your Schema version is 0.36.0.

### ISSUE THREAD

**Issue by yyh-sjtu** [siliconcompiler/siliconcompiler#2050]
Dear developer:
I used to run the flow by remote server successfully. But today, when I run the same script. I find the problem:"siliconcompiler._common.SiliconCompilerError: Server responded with 400: Error: Submitted jobs must use Schema version 0.37.x. Your Schema version is 0.36.0."
![J5X%39E@~M4`OY@A}`MX~{0](https://github.com/siliconcompiler/siliconcompiler/assets/131600287/f85f0f77-9e7e-4881-8c28-e250b79f7c76)
How can I deal with it.

**Comment by gadfort** [comment]
@yyh-sjtu you will need to update your SC version to atleast the 0.16.0 release.

**Comment by yyh-sjtu** [comment]
> @yyh-sjtu you will need to update your SC version to atleast the 0.16.0 release.

OK, thank you very much. I will try.
