### ISSUE TITLE
Error about running the design flow of a buffer.

### ISSUE THREAD

**Issue by yyh-sjtu** [siliconcompiler/siliconcompiler#2080]
![cd80f981b9bcbda1082a8bf6d786145](https://github.com/siliconcompiler/siliconcompiler/assets/131600287/ab7940ef-59a0-46ff-90e7-aa18555c0b61)
![6f21b781ec6ec66a93cb0d05e9a0c19](https://github.com/siliconcompiler/siliconcompiler/assets/131600287/fc9a3b37-0c6f-4663-85bb-ed0eefa595d3)
![db6fc14f7c3d78e140852a9bb50da7b](https://github.com/siliconcompiler/siliconcompiler/assets/131600287/fc8a1a73-5e05-4595-bae9-dc73c031ccd8)
Excuse me, let me ask a question. As the pictures shown, this design realizes a buffer. Why the server reports error?

**Comment by gadfort** [comment]
@yyh-sjtu sorry for the delay, a single buffer should not be a problem, but we seem to have some issues returning results reliably at the moment

**Comment by gadfort** [comment]
I hope things became more stable and you were able to run your design. Please reopen or open a new issue if you are still encountering issues.
