### ISSUE TITLE
STA after synthesis run

### ISSUE THREAD

**Issue by sebinho** [siliconcompiler/siliconcompiler#2382]
Hi,

From what I can gather, there isn't any timing report post-synthesis. The timing report seems to only come once we go through the floorplanning step.
This is often interesting to get some timing information early in the design phases. I see this is for example done in the OpenLane project where they do openSTA post synthesis and post routing.

I am open to contribute and write some scripts for this but I was wondering if there is any plan or progress on this matter @gadfort?
I suppose a good starting point would be to reuse part of the commands in `sc_metrics.tcl`.

This is the file used in OpenLane to perform this:
https://github.com/The-OpenROAD-Project/OpenLane/blob/337ffbf4749b8bc6e8d8742ed9a595934142198b/scripts/openroad/sta/multi_corner.tcl

Many thanks for your time.

**Comment by gadfort** [comment]
@sebinho it's a good idea, for the post route, the export task technically accomplishes this.  I don't have any plans to implement this, so if you have the time, I would be happy to review the PR.
I would suggest starting with just an openroad task, adding an opensta driver would be nice, but also a little bit more work.

**Comment by sebinho** [comment]
@gadfort, I created a pull request with all my changes. It is working fine for me, maybe there are things that you would like to change so please take a look at it.
The only thing that is not perfect is that it reports a utilization of -100% due to the fact that at that stage there isn't any core/die area defined. If you you have a workaround, please let me know.
Here is the pull request: https://github.com/siliconcompiler/siliconcompiler/pull/2389
