### ISSUE TITLE
Support for other HDLs

### ISSUE THREAD

**Issue by Andrea-Spitale** [siliconcompiler/siliconcompiler#2957]
### Feature Description

Hi,
The fact that your flow supports different design languages is really great.
 I wonder if there is any plan to support other languages such as spinalHDL, rohd, veryl?

Is it perhaps something a user could work on and file a pull request?

Thank you!

**Comment by gadfort** [comment]
@Andrea-Spitale we would love to support more languages, where practical.  As long as the tool chain is open source (so we can have it in our CI) we would be happy to take a pull request for it.
