### ISSUE TITLE
Add example for vivado workflow?

### ISSUE THREAD

**Issue by oddcoder** [siliconcompiler/siliconcompiler#3001]
### Version

Version: 0.28.7 

### On which OS did this happen?

Linux

### On which Python version did this happen?

Python 3.12

### Reproduction Steps

I have 1 day worth of experience with silicon compiler and hardware design in general, I am trying to get it to work with vivado (for some definition of work). 

I have Arty A7-100T board. And I am trying this script:
```python
 #!/usr/bin/env python3

from siliconcompiler import Chip
from siliconcompiler.targets import fpgaflow_demo
import os
import subprocess
import sys


if __name__ == "__main__":
    os.environ['PATH']='/root/.local/bin:'+os.environ['PATH']
    os.environ['LD_LIBRARY_PATH'] = "/root/.local/lib"
    chip = Chip('heartbeat')
    chip.set('fpga', 'partname', 'xc7a100tcsg324')
    chip.use(fpgaflow_demo)
    chip.input('heartbeat.v')                 # define list of source files
    chip.clock('clk', period=10)              # define clock speed of desig                                # run compilation of design and target
    chip.run()                                # run compilation of design and target
    chip.summary()                            # print results summary
```
I am not sure if I am doing anything wrong

### Expected Behavior

I am not fully sure what to expect at minimum vivado project files to load into vivado and do synthesis, at best files to flash on the fpga.

### Actual Behavior

It is very unlikely that this is a bug. Bu this is the output I get

```
| ERROR   | xc7a100tcsg324 has not been loaded
| ERROR   | Unable to run setup() for siliconcompiler.targets.fpgaflow_demo
Traceback (most recent call last):
  File "/mnt/oddrv64/heartbeat.py", line 15, in <module>
    chip.use(fpgaflow_demo)
  File "/usr/local/lib/python3.12/dist-packages/siliconcompiler/core.py", line 616, in use
    raise e
  File "/usr/local/lib/python3.12/dist-packages/siliconcompiler/core.py", line 610, in use
    use_modules = func(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/siliconcompiler/targets/fpgaflow_demo.py", line 34, in setup
    raise SiliconCompilerError(f'{part_name} has not been loaded', chip=chip)
siliconcompiler._common.SiliconCompilerError: xc7a100tcsg324 has not been loaded
```

**Comment by gadfort** [comment]
@oddcoder we don't have a full library of FPGAs in the demo. It's only: https://github.com/siliconcompiler/siliconcompiler/blob/main/siliconcompiler/fpgas/lattice_ice40.py

You will need to make an FPGA part driver for the Arty family of parts. Since you are going through vivado, I think you could get away with a really simple driver:
```
def setup():
    return FPGA('xc7a100tcsg324')
```

**Comment by gadfort** [comment]
I've removed the requirement for the FPGA part in https://github.com/siliconcompiler/siliconcompiler/pull/3014
That should be a start.

**Comment by gadfort** [comment]
#3015 contains a vivado example as well.
