### ISSUE TITLE
Silicon Compiler Server not working 

### ISSUE THREAD

**Issue by Subashkatel** [siliconcompiler/siliconcompiler#3062]
### Version

0.28.9

### On which OS did this happen?

macOS

### On which Python version did this happen?

Python 3.10

### Reproduction Steps

Add ```chip.set('option', 'remote', True)``` on heartbeat.py before line 13
Then run  the heartbeat example by doing ```python heartbeat.py``` 

### Expected Behavior

![image](https://github.com/user-attachments/assets/90d5f9da-ac88-4407-b5b5-b57e4096ca9f)

### Actual Behavior

Its suppose to run the example and provide the output but its stuck in a loop

**Comment by gadfort** [comment]
@Subashkatel I'll restart the runners and that should restart the queue, but you may need to resubmit your job since it looks like the jobqueue needs to be reset as well.

**Comment by Subashkatel** [comment]
Okay thank you

**Comment by gadfort** [comment]
I'll let you know once the runners are back up.

**Comment by gadfort** [comment]
@Subashkatel runners should be back up and accepting jobs

**Comment by dkongg** [comment]
Hello @gadfort, I am also unable to run the heartbeat example.
My job ID is f20844201a394953ade09403ff30d1a6 and python version is 3.11.11.
Could you look into the issue? Thanks

**Comment by gadfort** [comment]
You will need to update to SC 0.29.0 for the server to accept the job. You can see the log (I think) in:
heartbeat/job0/configs/siliconcompiler.log

**Comment by gadfort** [comment]
I've noticed some issues with power grid generation, which I'm taking a look at as well.
