### ISSUE TITLE
Can't find writecfg/readcfg functions

### ISSUE THREAD

**Issue by olofk** [siliconcompiler/siliconcompiler#798]
Docs point to writecfg/readcfg for JSON loading and dumping but I can't find these functions in the source.

**Comment by aolofsson** [comment]
Looks like that is from an outdated parameter definition in the schema. The right terms are read_manifest() and write_manifest() Thanks for letting me know! I have fixed it in the branch I am working on, it will be in main soon. 

All public methods are defined here: https://docs.siliconcompiler.com/en/latest/reference_manual/core_api.html

**Comment by aolofsson** [comment]
Fixed in commit
1b8d84fff27d3ca0aa7622aaf540b1b21400b2ed
