### ISSUE TITLE
error in calc_dpw

### ISSUE THREAD

**Issue by maliberty** [siliconcompiler/siliconcompiler#820]
I was just looking through your code and noticed that calc_dpw appears to have a bug:

            while math.hypot(0, y) < radius:
                y = y + yincr
                while math.hypot(x, y) < radius:
                    x = x + xincr
                    dies = dies + 1

you are using the value of x that represents the inside corner not the outside corner in your calculation.  A extreme example is  a die of radius x radius/2 would have 0 per wafer but this function would return 4.

In the case of Y it is just inefficient to check a row that can never succeed.  Both values should be pre-incremented before checking.

**Comment by aolofsson** [comment]
Nice catch! I will go back and fix it properly. This was wip 6 months ago, and it looks like I never completed it. There is no unit test for it.
