### ISSUE TITLE
Consider providing a conda environment.yml which creates an environment including all needed open source EDA tools

### ISSUE THREAD

**Issue by mithro** [siliconcompiler/siliconcompiler#906]
Thanks to the work by @proppy tools like OpenROAD, the SkyWater PDK, Magic, Netgen, etc are all now packaged in conda @ https://github.com/hdl/conda-eda -- There are even packages for cross compilers for things like RISC-V architecture which can be found @ https://github.com/hdl/conda-compilers

This means that silicon compiler could provide a conda environment.yml file (https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#create-env-file-manually) which installs all the requirements needed to run Silicon Compiler.

**Comment by proppy** [comment]
additionally maybe also consider packaging siliconcompiler w/ a [recipe](https://docs.conda.io/projects/conda-build/en/latest/concepts/recipe.html) that depends on the external tools listed here https://docs.siliconcompiler.com/en/latest/user_guide/installation.html#external-tools, so that people could do `conda install siliconcompiler` to get a full blown installation.

**Comment by aolofsson** [comment]
Interesting! There are quite a lot of tricky dependancies between the tool versions that we are running into. We'll take a look to see how much work it would be. This does require peple to use conda, which is a barrier to some. (but perhaps not a big one?)

**Comment by mithro** [comment]
@aolofsson -- Conda is pretty common and well accepted in the ML and scientific worlds. Like all packaging systems it has some people who hate it.

**Comment by mithro** [comment]
FYI - @proppy

**Comment by mithro** [comment]
Please do report the issue on the upstream repositories!

I have asked @proppy to look into what is going on here. I believe it is because these packages are still very new (less than a week old) and need a little bit more work. The only way things will get better is to have users finding and reporting these issues!

**Comment by proppy** [comment]
@WRansohoff some of those package do depend on conda-forge you confirm if/this also happen when using a conda-forge based environment? (either by using https://github.com/conda-forge/miniforge#miniforge3 or folllowing https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge)

**Comment by WRansohoff** [comment]
Ah, I must have missed that dependency. Using conda-forge to install the packages seems to work, e.g.:

    conda install -c conda-forge --channel "LiteX-Hub" openroad

Thank you for the clarification, and for packaging open-source EDA tools like this!

We might want to look into packaging specific versions of the tools to ensure compatibility with our scripts - it looks like the conda scripts build yosys, openroad, etc from the tip of main. But it looks like the conda-eda README contains instructions for

**Comment by proppy** [comment]
> We might want to look into packaging specific versions of the tools to ensure compatibility with our scripts - it looks like the conda scripts build yosys, openroad, etc from the tip of main.

The intent behind this versioning schema is that https://github.com/hdl/conda-eda/actions build intermediate version daily and version them against the output of `git-describe` before uploading them https://anaconda.org/LiteX-Hub/repo.

That allows us to get most of the intermediate version packages, see for example https://anaconda.org/LiteX-Hub/magic/files.

Downstream tools (like siliconcompiler) are then free to depends on the (range of) version(s) they've been QA'ed against by specifying an explicit version constraint: https://docs.conda.io/projects/conda-build/en/latest/resources/package-spec.html#package-match-specifications

**Comment by WRansohoff** [comment]
Great, thank you!

We have a few things to work out before we can fully support using `conda env create` to setup a working dev environment, but your recipes made it easy to get most of the way there with a very small script!

**Comment by siddharth-joshi** [comment]
Hi all, really appreciate the work you've all been doing. I was curious if there has been movement here? I'm about to embark on a fresh install so was curious re: if SC had been included in conda?

**Comment by gadfort** [comment]
File is provided in: https://github.com/siliconcompiler/siliconcompiler/blob/main/setup/conda/environment.yml
However, it appears several of the conda-hdl tools have stopped getting updated.
