### ISSUE TITLE
OpenROAD sc_display.tcl is inconsistent with schema

### ISSUE THREAD

**Issue by arlpetergadfort** [siliconcompiler/siliconcompiler#930]
https://github.com/siliconcompiler/siliconcompiler/blob/a202264ed29cbb960d85fad3be29cd071d4e66b2/siliconcompiler/tools/openroad/sc_display.tcl#L37

Should have stackup as well.

Additionally, it would be nice if the liberty files were loaded along with the sdc file.

**Comment by nmoroze** [comment]
I think we might actually be able to just get rid of sc_display.tcl and reuse sc_apr.tcl setup here. I'll do some experimenting.

**Comment by nmoroze** [comment]
Opened a PR implementing this. One thing to keep in mind is that show spawns a new step, meaning any SDC files fed in on a per-step basis using the 'read', 'sdc' schema won't be loaded. However, things fed in via 'constraints' will be. I'm not sure if this works for your use case, I also think this subtle distinction might trip people up.

**Comment by nmoroze** [comment]
#933 is merged, closing.
