### ISSUE TITLE
submit example design to the next MPW shuttle?

### ISSUE THREAD

**Issue by proppy** [siliconcompiler/siliconcompiler#948]
Curious if you've consider submitting some of the examples designs in https://github.com/siliconcompiler/siliconcompiler/tree/main/examples to the Open MPW shuttle: https://efabless.com/open_shuttle_program/ ?

That would be an interesting way to ensure that not too many assumption about specific tooling are baked into the current precheck and submission process.

**Comment by aolofsson** [comment]
It's a good idea. Right now we are too swamped with contract commitments and building out the platform for other commercial nodes, but when the time is right, we will give it a shot.
