### ISSUE TITLE
write_def() not working?

### ISSUE THREAD

**Issue by AllenDBoston** [siliconcompiler/siliconcompiler#955]
Below is the code I'm using to generate a gds, def, and let for my design. It seems that the resulting def is site array only no components etc..

#!/bin/env python3.9

import siliconcompiler
from   siliconcompiler.floorplan import Floorplan
import shutil
import os

from sources import add_sources

def main():

    # define the chip instance, target, and design name
    chip = siliconcompiler.Chip(loglevel='INFO')

    # Options
    chip.set('relax', 'true')
    chip.set('quiet', 'true')

    chip.load_target("skywater130_demo")
    chip.set('eda', 'openroad', 'variable', 'place', '0', 'place_density', ['0.60'])
    chip.set('eda', 'openroad', 'variable', 'route', '0', 'grt_allow_congestion', ['true'])

    chip.set('design', 'fpga_top')
    chip.set('source', 'SRC/fpga_top.v')
    chip.write_manifest('manifest.json')

    chip.clock(name='core_clk', pin='clk', period=20)

    add_sources(chip)

    fp = Floorplan(chip)

    x = 550

    diearea  = [(0, 0), (x, x)]
    corearea = [(0, 0), (x, x)]

    fp.create_diearea(diearea, corearea=corearea)
    chip.set('asic', 'diearea',  [(0,0), (x, x)])
    chip.set('asic', 'corearea', [(0,0), (x, x)])

    fp.write_lef("fpga_top.lef")
    fp.write_def("fpga_top.def")

    chip.run()
    chip.set('read', 'def', 'floorplan', '0', 'fpga_top.def')

    # Copy generated files out of build directory into current working directory
    gds = chip.find_result('gds', step='export')
    netlist = chip.find_result('vg', step='dfm')
    shutil.copy(gds, 'fpga_top.gds')
    shutil.copy(netlist, 'upw.vg')

    #chip.summary()

if __name__ == '__main__':
    main()

**Comment by WRansohoff** [comment]
To summarize some out-of-band discussion, the following block generates an empty floorplan with a specified die size:

```
fp = Floorplan(chip)

x = 550

diearea  = [(0, 0), (x, x)]
corearea = [(0, 0), (x, x)]

fp.create_diearea(diearea, corearea=corearea)
chip.set('asic', 'diearea',  [(0,0), (x, x)])
chip.set('asic', 'corearea', [(0,0), (x, x)])
```

To add more features such as pins or tracks, [the Python floorplanning AP](https://docs.siliconcompiler.com/en/latest/tutorials/zerosoc.html)I must be used. And to use a DEF floorplan in a job run, the `chip.run()` call must go after all of the `chip.set(...)` calls, including this one:

    chip.set('read', 'def', 'floorplan', '0', 'fpga_top.def')

Unfortunately, we do not yet support some of the functionality that it sounds like you need. Namely, we cannot currently read in a DEF floorplan, modify it, and write out an updated DEF file. We will continue to investigate such functionality.
