### ISSUE TITLE
Improve summary metric readability

### ISSUE THREAD

**Issue by aolofsson** [siliconcompiler/siliconcompiler#985]
The units for the current summary  (and metrics ) are non-obvious. Instead of hard coding units on a per metric basis, we should:

 1.) Respect the units dictionary when capturing metrics in the post_process() step 
 2.) Display a column with units in summary()
 3.) Add a "unit" field in each metric to specify the unit of measurement (time, count, percentage, power, length, area, ...)
 4.) Hard code trace time and memory since these are controlled by runtask()

**Comment by gadfort** [comment]
Closed with https://github.com/siliconcompiler/siliconcompiler/pull/1384
