### ISSUE TITLE
Command line program sc not handling spaces in fields

### ISSUE THREAD

**Issue by aolofsson** [siliconcompiler/siliconcompiler#996]
Place holder. Need a better way of differentiating between "keys" provided at the command line and free string arguments. 
Fails on ['package', 'description']

https://github.com/siliconcompiler/siliconcompiler/blob/fec19aecb4962f439cecdf1fca70a7e89229b9ff/siliconcompiler/core.py#L404-L413

**Comment by nmoroze** [comment]
Will take a look at this, need to fix a few other things in create_cmdline() anyway:

- inferring filetype of sources
- making switchlist behavior consistent with docs
